# **Curso de Machine Learning - IA Expert Academy**


---


**Aluno:** Lucas Dias Noronha

# **Salvar um classificador já treinado**

Com os melhores modelos e parâmetros definidos, agora é o momento de salvar os modelos de classificação para a base de crédito. Esses modelos poderão ser utilizados com dados reais e enviados ao desenvolvedor responsável por criar uma interface gráfica para os usuários.

Os modelos selecionados são:

SVM (Máquina de Vetores de Suporte)

Árvore de Decisão

Redes Neurais

Cada um desses modelos foi treinado com os dados da base de crédito e ajustado com os melhores parâmetros identificados durante a avaliação. Agora, salvarei esses modelos em arquivos para uso futuro.

> Atenção: certifique-se de armazenar os modelos em locais adequados e de fornecer instruções claras ao desenvolvedor sobre como carregar e utilizar esses modelos nas interfaces gráficas ou em outras aplicações. Esses modelos fornecerão a capacidade de realizar classificações precisas e ajudarão a tomar decisões informadas com base nos dados de crédito.



In [6]:
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

import pickle
import numpy as np

## **Preparandos os Dados**

In [4]:
# Carregando os dados de treinamento e teste.
with open('credit.pkl', 'rb') as f:
  X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste = pickle.load(f)

In [12]:
# Juntando todos os dados previsores e classificadores que foram separados anteriormente.
X_credit = np.concatenate((X_credit_treinamento, X_credit_teste), axis = 0)
y_credit = np.concatenate((y_credit_treinamento, y_credit_teste), axis = 0)

In [8]:
X_credit.shape, y_credit.shape # Podemos constatar que os dados estão juntos novamente.

((2000, 3), (2000,))

## **Preparando os modelos de Classificador**

In [15]:
# Treinando o modelo de Rede Neural (Multi-Layer Perceptron).
classificador_rede_neural = MLPClassifier(activation='relu', batch_size = 56, solver='adam')
classificador_rede_neural.fit(X_credit, y_credit)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(batch_size=56)

In [16]:
# Treinando o modelo de Árvore de decisão.
classificador_arvore = DecisionTreeClassifier(criterion='entropy', min_samples_leaf=1, min_samples_split=5, splitter='best')
classificador_arvore.fit(X_credit, y_credit)

DecisionTreeClassifier(criterion='entropy', min_samples_split=5)

In [17]:
# Treinando o modelo de SVM (Suport Vector Machine).
classificador_svm = SVC(C = 2.0, kernel='rbf', probability=True)
classificador_svm.fit(X_credit, y_credit)

SVC(C=2.0, probability=True)

## **Salvandos os Modelos de Classificador**

Salvarei os modelos de classificação treinados. Os modelos serão salvos em arquivos com extensão ".sav".


In [14]:
# Salvando o modelo de Rede Neural
pickle.dump(classificador_rede_neural, open('rede_neural_finalizado.sav', 'wb'))

# Salvando o modelo de Árvore de Decisão
pickle.dump(classificador_arvore, open('arvore_finalizado.sav', 'wb'))

# Salvando o modelo de SVM
pickle.dump(classificador_svm, open('svm_finalizado.sav', 'wb'))

Os modelos de classificação treinados podem ser carregados posteriormente para realizar previsões em dados reais. Certifique-se de ter importado a biblioteca pickle antes de executar o código.

# **Instruções para carregar um classificador já treinado**

Carregarei os modelos de classificação treinados. Os modelos serão atribuídos às variáveis "rede_neural", "arvore" e "svm". Eles poderão ser usados para fazer previsões em novos dados.

> Atenção: certifique-se de que os arquivos .sav estejam no diretório correto.

## **Carregando modelos**

In [19]:
# Carregando os modelos de classificação treinados.

# Carregando o modelo de Rede Neural.
rede_neural = pickle.load(open('rede_neural_finalizado.sav', 'rb'))

# Carregando o modelo de Árvore de Decisão.
arvore = pickle.load(open('arvore_finalizado.sav', 'rb'))

# Carregando o modelo de SVM (Suport Vector Machine).
svm = pickle.load(open('svm_finalizado.sav', 'rb'))

## **Simulando um novo cliente**

Irei carregar o registro 1999 da base X_credit para  fazer uma simulação de um novo cliente e mostrar como os modelos funcionam.

In [20]:
# Carregando registro.
novo_registro = X_credit[1999]

# Retornando registro.
novo_registro

array([-1.03572293, -0.93978122,  0.04244312])

In [22]:
novo_registro.shape # Array simples com uma dimensão.

(3,)

In [25]:
# Tranformando em um array de duas dimensões para podermos fazer a previsão.
novo_registro = novo_registro.reshape(1, -1)

novo_registro.shape # Retornará uma linha e três colunas.

(1, 3)

In [26]:
novo_registro # Podemos verificar que agora possui dois colchetes, o que indica que agora temos em formato de matriz.

array([[-1.03572293, -0.93978122,  0.04244312]])

In [27]:
# Realizarei a previsão do novo registro utilizando o modelo de classificação "Rede Neural".
rede_neural.predict(novo_registro)

array([1])

In [30]:
# Realizarei a previsão do novo registro utilizando o modelo de classificação "Árvore de Decisão".
arvore.predict(novo_registro)

array([1])

In [31]:
# Realizarei a previsão do novo registro utilizando o modelo de classificação "SVM".
svm.predict(novo_registro)

array([1])

Podemos constatar que todos os três modelos classificaram que o novo cliente como "não pagará o emprestimo".

In [37]:
# Carregando registro.
novo_registro = X_credit[0]

# Retornando registro.
novo_registro

array([-1.3754462 ,  0.50631087,  0.10980934])

In [38]:
# Tranformando em um array de duas dimensões para podermos fazer a previsão.
novo_registro = novo_registro.reshape(1, -1)

In [39]:
# Realizarei a previsão do novo registro utilizando o modelo de classificação "Rede Neural".
rede_neural.predict(novo_registro)

array([0])

In [40]:
# Realizarei a previsão do novo registro utilizando o modelo de classificação "Árvore de Decisão".
arvore.predict(novo_registro)

array([0])

In [41]:
# Realizarei a previsão do novo registro utilizando o modelo de classificação "SVM".
svm.predict(novo_registro)

array([0])

Podemos constatar que todos os três modelos classificaram esse novo registro de cliente como "irá pagar o empréstimo"

Foi mostrado como os modelos poderão ser carregados, além de uma simulação do funcionamento dos modelos.

# **Considerações Finais**

Neste estudo de caso, pude aprender a importante etapa de salvar e carregar modelos de classificação de machine learning. Essa habilidade é fundamental para armazenar e reutilizar os modelos treinados, permitindo sua aplicação em novos dados e cenários. Com essa técnica, tenho agora a capacidade de aproveitar ao máximo os modelos desenvolvidos, garantindo sua reprodutibilidade e possibilitando sua utilização em diferentes contextos.

Agradeço ao professor Jones Granatyr pelo conhecimento compartilhado e pela orientação durante o curso. Essa experiência contribuiu significativamente para minha compreensão de algoritmos de Machine Learning e sua aplicação prática.